### ISSUE TITLE
Crash upon starting an old or new world when having downloaded mod for the first time

### ISSUE THREAD

**Issue by JelliBelli123** [SpaceGameDev568/Factory_Prop_Mod#1]
This specifically was when launching a new world. vvvvvvvvv Crash report for launching old vanilla world below it.

Version: 176027, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: Standalone, IsUsingMods: Yes

Fatal error: [File:E:/SatisfactoryModding/SMLBuildTest/Plugins/SML/Source/SML/Private/Registry/ModContentRegistry.cpp] [Line: 425] Attempt to register invalid content in mod content registry: Schematic '/Factory_Prop_Mod/FactoryDecorMod/PlantModContent/0Schematics/FactoryPlantUnlock.FactoryPlantUnlock_C' registered by Factory_Prop_Mod references invalid NULL Recipe in it's Unlocks Array. Script callstack: Unable to display Script Callstack. Compile with DO_BLUEPRINT_GUARD=1

FactoryGame_SML_Win64_Shipping!AModContentRegistry::RegisterSchematic() [E:\SatisfactoryModding\SMLBuildTest\Plugins\SML\Source\SML\Private\Registry\ModContentRegistry.cpp:424]
FactoryGame_SML_Win64_Shipping!UGameWorldModule::RegisterDefaultContent() [E:\SatisfactoryModding\SMLBuildTest\Plugins\SML\Source\SML\Private\Module\GameWorldModule.cpp:38]
FactoryGame_SML_Win64_Shipping!UGameWorldModule::DispatchLifecycleEvent() [E:\SatisfactoryModding\SMLBuildTest\Plugins\SML\Source\SML\Private\Module\GameWorldModule.cpp:15]
FactoryGame_KBFL_Win64_Shipping!<lambda_4e1a232d9d611eb6b77de85fc308afcd>::operator()<CallScope<void (__cdecl*)(UWorldModuleManager *,enum ELifecyclePhase)> >() [D:\SFModding\Update5\Plugins\KBFL\Source\KBFL\Private\KBFLModule.cpp:33]
FactoryGame_KBFL_Win64_Shipping!HookInvokerExecutorMemberFunction<void (__cdecl UWorldModuleManager::*)(enum ELifecyclePhase),&UWorldModuleManager::DispatchLifecycleEvent,0,void,UWorldModuleManager,enum ELifecyclePhase>::applyCallVoid() [D:\SFModding\Update5\Plugins\SML\Source\SML\Public\Patching\NativeHookManager.h:303]
FactoryGame_SML_Win64_Shipping!UWorldModuleManager::InitializeModules() [E:\SatisfactoryModding\SMLBuildTest\Plugins\SML\Source\SML\Private\Module\WorldModuleManager.cpp:52]
FactoryGame_SML_Win64_Shipping!TBaseUObjectMethodDelegateInstance<0,UWorldModuleManager,void __cdecl(UWorld::FActorsInitializedParams const &),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [E:\SatisfactoryModding\Unreal Engine - CSS\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:611]
FactoryGame_Engine_Win64_Shipping!TMulticastDelegate<void __cdecl(UActorComponent *),FDefaultDelegateUserPolicy>::Broadcast() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Core\Public\Delegates\DelegateSignatureImpl.inl:955]
FactoryGame_Engine_Win64_Shipping!UWorld::InitializeActorsForPlay() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Engine\Private\World.cpp:4408]
FactoryGame_Engine_Win64_Shipping!UEngine::LoadMap() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Engine\Private\UnrealEngine.cpp:13185]
FactoryGame_FactoryGame_Win64_Shipping!UFGGameEngine::LoadMap() [D:\ws\SB-211116092526-440\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGGameEngine.cpp:32]
FactoryGame_Engine_Win64_Shipping!UEngine::Browse() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Engine\Private\UnrealEngine.cpp:12430]
FactoryGame_Engine_Win64_Shipping!UEngine::TickWorldTravel() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Engine\Private\UnrealEngine.cpp:12628]
FactoryGame_Engine_Win64_Shipping!UGameEngine::Tick() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Engine\Private\GameEngine.cpp:1794]
FactoryGame_FactoryGame_Win64_Shipping!UFGGameEngine::Tick() [D:\ws\SB-211116092526-440\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGGameEngine.cpp:16]
FactoryGame_Win64_Shipping!FEngineLoop::Tick() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:4896]
FactoryGame_Win64_Shipping!GuardedMain() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Launch\Private\Launch.cpp:169]
FactoryGame_Win64_Shipping!GuardedMainWrapper() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:137]
FactoryGame_Win64_Shipping!WinMain() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:268]
FactoryGame_Win64_Shipping!__scrt_common_main_seh() [d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

Launching old vanilla world crash report: vvvvvvvvvv

Version: 176027, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: Standalone, IsUsingMods: Yes

Fatal error: [File:E:/SatisfactoryModding/SMLBuildTest/Plugins/SML/Source/SML/Private/Registry/ModContentRegistry.cpp] [Line: 425] Attempt to register invalid content in mod content registry: Schematic '/Factory_Prop_Mod/FactoryDecorMod/PlantModContent/0Schematics/FactoryPlantUnlock.FactoryPlantUnlock_C' registered by Factory_Prop_Mod references invalid NULL Recipe in it's Unlocks Array. Script callstack: Unable to display Script Callstack. Compile with DO_BLUEPRINT_GUARD=1

FactoryGame_SML_Win64_Shipping!AModContentRegistry::RegisterSchematic() [E:\SatisfactoryModding\SMLBuildTest\Plugins\SML\Source\SML\Private\Registry\ModContentRegistry.cpp:424]
FactoryGame_SML_Win64_Shipping!UGameWorldModule::RegisterDefaultContent() [E:\SatisfactoryModding\SMLBuildTest\Plugins\SML\Source\SML\Private\Module\GameWorldModule.cpp:38]
FactoryGame_SML_Win64_Shipping!UGameWorldModule::DispatchLifecycleEvent() [E:\SatisfactoryModding\SMLBuildTest\Plugins\SML\Source\SML\Private\Module\GameWorldModule.cpp:15]
FactoryGame_KBFL_Win64_Shipping!<lambda_4e1a232d9d611eb6b77de85fc308afcd>::operator()<CallScope<void (__cdecl*)(UWorldModuleManager *,enum ELifecyclePhase)> >() [D:\SFModding\Update5\Plugins\KBFL\Source\KBFL\Private\KBFLModule.cpp:33]
FactoryGame_KBFL_Win64_Shipping!HookInvokerExecutorMemberFunction<void (__cdecl UWorldModuleManager::*)(enum ELifecyclePhase),&UWorldModuleManager::DispatchLifecycleEvent,0,void,UWorldModuleManager,enum ELifecyclePhase>::applyCallVoid() [D:\SFModding\Update5\Plugins\SML\Source\SML\Public\Patching\NativeHookManager.h:303]
FactoryGame_SML_Win64_Shipping!UWorldModuleManager::InitializeModules() [E:\SatisfactoryModding\SMLBuildTest\Plugins\SML\Source\SML\Private\Module\WorldModuleManager.cpp:52]
FactoryGame_SML_Win64_Shipping!TBaseUObjectMethodDelegateInstance<0,UWorldModuleManager,void __cdecl(UWorld::FActorsInitializedParams const &),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [E:\SatisfactoryModding\Unreal Engine - CSS\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:611]
FactoryGame_Engine_Win64_Shipping!TMulticastDelegate<void __cdecl(UActorComponent *),FDefaultDelegateUserPolicy>::Broadcast() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Core\Public\Delegates\DelegateSignatureImpl.inl:955]
FactoryGame_Engine_Win64_Shipping!UWorld::InitializeActorsForPlay() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Engine\Private\World.cpp:4408]
FactoryGame_Engine_Win64_Shipping!UEngine::LoadMap() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Engine\Private\UnrealEngine.cpp:13185]
FactoryGame_FactoryGame_Win64_Shipping!UFGGameEngine::LoadMap() [D:\ws\SB-211116092526-440\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGGameEngine.cpp:32]
FactoryGame_Engine_Win64_Shipping!UEngine::Browse() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Engine\Private\UnrealEngine.cpp:12430]
FactoryGame_Engine_Win64_Shipping!UEngine::TickWorldTravel() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Engine\Private\UnrealEngine.cpp:12628]
FactoryGame_Engine_Win64_Shipping!UGameEngine::Tick() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Engine\Private\GameEngine.cpp:1794]
FactoryGame_FactoryGame_Win64_Shipping!UFGGameEngine::Tick() [D:\ws\SB-211116092526-440\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGGameEngine.cpp:16]
FactoryGame_Win64_Shipping!FEngineLoop::Tick() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:4896]
FactoryGame_Win64_Shipping!GuardedMain() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Launch\Private\Launch.cpp:169]
FactoryGame_Win64_Shipping!GuardedMainWrapper() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:137]
FactoryGame_Win64_Shipping!WinMain() [D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:268]
FactoryGame_Win64_Shipping!__scrt_common_main_seh() [d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by Ackros** [comment]
having exact same issue, resturning to game after a long hiatus... update 5 CL176089.282 SML3.3.0

Factory props 1 of 95 being loaded.

SMM profile export :

manifest.json{"manifestVersion":2,"items":[{"id":"UnlockAllAlternateRecipes","enabled":true},{"id":"SafeTWalkways","enabled":true},{"id":"FloorHole","enabled":true},{"id":"GridRuler","enabled":true},{"id":"WaterPool","enabled":true},{"id":"SS_Mod","enabled":true},{"id":"ResourceNodeCreator","enabled":true},{"id":"UtilityMod","enabled":true},{"id":"IconSign","enabled":true},{"id":"HardDriveComputer","enabled":true},{"id":"HugeStorage","enabled":true},{"id":"GhostConstruction","enabled":true},{"id":"DeepMining","enabled":true},{"id":"CoveredConveyor","enabled":true},{"id":"BigStorageTank","enabled":true},{"id":"CheapSmartSplitter","enabled":true},{"id":"DaisyChainPowerCables","enabled":true},{"id":"AllNodesPure","enabled":true},{"id":"MultiSplitterAndMerger","enabled":true},{"id":"FastCraftBench","enabled":true},{"id":"HardDriveCheat","enabled":true},{"id":"MagicMachine","enabled":true},{"id":"MultidimensionalFactory","enabled":true},{"id":"HundredTimesAwesomePoints","enabled":true},{"id":"MinerMk5","enabled":true},{"id":"Stats","enabled":true},{"id":"TenTimesAwesomePoints","enabled":true},{"id":"ExtendableWalkway","enabled":true},{"id":"PersonalDrones","enabled":true},{"id":"LogisticDrones","enabled":true},{"id":"MirroredBuildings","enabled":true},{"id":"NoRocks","enabled":true},{"id":"InitialBus","enabled":true},{"id":"ZipStrips","enabled":true},{"id":"EarlyHover","enabled":true},{"id":"CCTV","enabled":true},{"id":"ModdedSavesChecker","enabled":true},{"id":"SlotMachine","enabled":true},{"id":"WallConveyorSupports","enabled":true},{"id":"QuantumCraft","enabled":true},{"id":"WallHoleConveyor","enabled":true},{"id":"HubTerminals","enabled":true},{"id":"MoreDecorations","enabled":true},{"id":"Kraigsta","enabled":true},{"id":"Wagons","enabled":true},{"id":"EarlyMap","enabled":true},{"id":"EarlyPowerStorage","enabled":true},{"id":"Teleporter","enabled":true},{"id":"WirelessLamps","enabled":true},{"id":"UpsideDownFoundations","enabled":true},{"id":"Letters","enabled":true},{"id":"AltRecipeResearch","enabled":true},{"id":"BigWalls","enabled":true},{"id":"AB_FluidExtras","enabled":true},{"id":"AB_CableMod","enabled":true},{"id":"JustTurbines","enabled":true},{"id":"UndergroundLogistics","enabled":true},{"id":"BeltfedBiomassBurner","enabled":true},{"id":"StorageTeleporter","enabled":true},{"id":"FasterManualCrafting","enabled":true},{"id":"BuildableResourceNodes","enabled":true},{"id":"BuildableResourceNodesAddon_MM","enabled":true},{"id":"LongerBeams","enabled":true},{"id":"WallPipeSupports","enabled":true},{"id":"SmartFoundations","enabled":true},{"id":"ShowEnemiesHealth","enabled":true},{"id":"TrainTable","enabled":true},{"id":"RSS","enabled":true},{"id":"FicsitFarming","enabled":true},{"id":"FicsItNetworks","enabled":true},{"id":"PowerControlRoom","enabled":true},{"id":"LinearMotion","enabled":true},{"id":"SmallTrainStation","enabled":true},{"id":"minerplus","enabled":true},{"id":"NoneEquipment","enabled":true},{"id":"Cellphone","enabled":true},{"id":"UndergroundBelts","enabled":true},{"id":"x3_lights","enabled":true},{"id":"ItemCounter","enabled":true},{"id":"SmartWirelessLighting","enabled":true},{"id":"MicrowavePower","enabled":true},{"id":"x3_splitter_merger_pole","enabled":true},{"id":"ContainerScreen","enabled":true},{"id":"Factory_Prop_Mod","enabled":true}]}PK

**Comment by SpaceGameDev568** [comment]
This issue was resolved in the latest patch (0.2.2)
