### ISSUE TITLE
[BUG] Can't rotate objects in BP Designer

### ISSUE THREAD

**Issue by Normi029-RTHERY** [SpaceGameDev568/Factory_Prop_Mod#17]
## Describe the bug

When trying to place any Factory_Prop object in the blueprint designer it can not be rotated despite working fine outside of the BP designer

---

## To Reproduce

Try to rotate a buildable from Factory_Prop in the BP designer in Satisfactory U8 [EA - CL264901 - SML v3.6.0]

---

## Multiplayer?

Noop

---

## Other Mods?

Noop, tested with Factory_Prop being the only mod installed

**Comment by SpaceGameDev568** [comment]
Found the issue, fixing and pushing a patch in a few minutes.

**Comment by SpaceGameDev568** [comment]
Fixed in v1.3.3
