### ISSUE TITLE
Factory props not aligning

### ISSUE THREAD

**Issue by JuliusZulauf** [SpaceGameDev568/Factory_Prop_Mod#19]
### Operating System

Winblows 10/11

### Environment

P2P Host (You are hosting a game locally and your friends are joining you)

### Game Version

Early Access

### SML Version

v3.7.0

### Mod Version

v1.3.10

### Describe the bug

Its not possible to align props perfectly staight exept on the blueprint desinger ground.
not even snap to guidelines is working.
my current workaround is creating a blueprint with just the prop and then using the blueprint to have an alignt prop.
![unalingt props](https://github.com/user-attachments/assets/a87fd8d0-7797-410f-b40a-aa743db8e646)

### Expected Behavior

i expected the props to align with the grid there placed on

### Contact agreement

- [X] I agree to allow the developer to contact me for more information regarding this bug if necessary.

**Comment by SpaceGameDev568** [comment]
Hi Julius, I managed to replicate this issue by placing the props on a foundation that was not aligned to the World Grid. You may be able to mitigate it by aligning your foundations to the world grid, while I look into a potential fix. Thank you for your report!

**Comment by SpaceGameDev568** [comment]
Fixed in Factory Props 2.0 for SML 3.8.0, which will be released Soon™.
