### ISSUE TITLE
Incompatibility with FICSIT Networks

### ISSUE THREAD

**Issue by bufu1337** [SpaceGameDev568/Factory_Prop_Mod#21]
### Operating System

Winblows 10/11

### Environment

Single Player

### Game Version

Experimental

### SML Version

v3.8.0

### Mod Version

v2.1.2

### Describe the bug

since update 1.0.5 i am getting an error with the initializing of FICSIT Networks.
i tried out to add only FICSIT Networks. and removed all other, and it work... so it must be only a incompatibility...
after readding each mod (~170) the issue cam up again with adding factory props...
So there is somehow an incompatibility and unfortunaetly i prefer FICSIT Networks more the Factory Props... especially i didnt use factory props, i was still plannign to decorate...
I would like to get factory props back again, please fix it

### Expected Behavior

It should load both mods, FICSIT Networks & Factory Props

### Contact agreement

- [X] I agree to allow the developer to contact me for more information regarding this bug if necessary.

**Comment by SpaceGameDev568** [comment]
What is the error you are recieving and can you provide your SMM debug info so I can better help you?

**Comment by bufu1337** [comment]
[FactoryGame.log](https://github.com/user-attachments/files/17891559/FactoryGame.log)
[new.txt](https://github.com/user-attachments/files/17891560/new.txt)
[UEMinidump.dmp](https://github.com/user-attachments/files/17891561/UEMinidump.dmp)
