### ISSUE TITLE
Ficsmas star is now invisible

### ISSUE THREAD

**Issue by batlham** [SpaceGameDev568/Factory_Prop_Mod#22]
### Operating System

Winblows 10/11

### Environment

Single Player

### Game Version

Early Access

### SML Version

3.0.3

### Mod Version

2.2.1

### Describe the bug

The Ficsmas Star is invisible. Other items work ok. All new stars are also invisible.

### Expected Behavior

To be visible like when I placed them early Dec.

### Contact agreement

- [X] I agree to allow the developer to contact me for more information regarding this bug if necessary.

**Comment by SpaceGameDev568** [comment]
Acknowledged, thanks for your report! I'll fix it as soon as I have time.

**Comment by batlham** [comment]
just noticed there are two different ficsmas stars... I was refering to the Ficsmas Wonder Star.

**Comment by SpaceGameDev568** [comment]
Thanks for the clarification. I'll see if I can address it over the weekend.

**Comment by batlham** [comment]
FYI Snowball Pile shows just one snowball... I just found it.. Been getting carried away with the mod :)

**Comment by SpaceGameDev568** [comment]
Thank you for your patience, this has now been fixed in the latest patch, v2.2.2.

**Comment by batlham** [comment]
Thank you 🥇 :)
![Screenshot20241215-21102700000](https://github.com/user-attachments/assets/9285220c-9f2e-4291-aa17-721ae0898af0)
